version: '3'

services:

  db_dev:
    image: mysql:8.0.12
    #        volumes:
    #          - "./volumes/mysql_dev:/var/lib/mysql"
    ports:
    - "3308:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=
    - MYSQL_DATABASE=db_dev
    - MYSQL_USER=root
    - MYSQL_PASSWORD=